//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberSmash.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NumberSmash.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you have enabled the “Extended Features Toggle”, there are also several special number types that can be introduced by enabling the &quot;Extended Features Toggle&quot;.
        /// </summary>
        internal static string ExtHelpLine1 {
            get {
                return ResourceManager.GetString("ExtHelpLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Infinitive (∞) - Can be combined with any other number, but does not count towards your score
        ///- Signum (±) - Represents both positive and negative versions of a number
        ///- Unknown (x) - Allows you to avoid losing a point one time if the sum is not 0.
        /// </summary>
        internal static string ExtHelpLine2 {
            get {
                return ResourceManager.GetString("ExtHelpLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Double ([×2]) - Doubles your score when used
        ///Null - Refreshes the equation without resetting the game
        ///- Multiplication of 0 ([×0]) - Same as Infinitive, but counts towards your score.
        /// </summary>
        internal static string ExtHelpLine3 {
            get {
                return ResourceManager.GetString("ExtHelpLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Smash.
        /// </summary>
        internal static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The objective of the game is to select a set of numbers that add up to 0. When the game begins, it will present you with an equation containing 7 numbers. Your goal is to select one or more numbers from the equation that, when added together, equal 0..
        /// </summary>
        internal static string HelpLine1 {
            get {
                return ResourceManager.GetString("HelpLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To play, simply click on the numbers you want to select. As long as the sum of the selected numbers is 0, you will earn 1 point and the equation will be refreshed with a new set of 7 numbers. If the sum of your selected numbers does not equal 0, you will lose the game..
        /// </summary>
        internal static string HelpLine2 {
            get {
                return ResourceManager.GetString("HelpLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are unable to find a set of numbers that add up to 0, you can click the &quot;Refresh&quot; button to generate a new equation. The game will check if there is a valid solution before refreshing..
        /// </summary>
        internal static string HelpLine3 {
            get {
                return ResourceManager.GetString("HelpLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To restart the game at any time, click the &quot;Reset&quot; button. You can also click the &quot;Help&quot; button to have the game automatically find a set of numbers that add up to 0..
        /// </summary>
        internal static string HelpLine4 {
            get {
                return ResourceManager.GetString("HelpLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additionally, the game includes several optional advanced features that can enhance the experience:
        ///- &quot;Select All&quot; checkbox to instantly select or deselect all numbers
        ///- &quot;Pause&quot; checkbox to pause the game
        ///- Timer that displays your score and time used.
        /// </summary>
        internal static string HelpLine5 {
            get {
                return ResourceManager.GetString("HelpLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Options to adjust font size, make the game always on top, show a progress bar, and display the current sum There are more options in the menu strip at the top.
        ///More options can be found on the menu strip at the top..
        /// </summary>
        internal static string HelpLine6 {
            get {
                return ResourceManager.GetString("HelpLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For extended features, you may check the “Extended Features Toggle”. For more information about this option, you may use this help again after checking this option..
        /// </summary>
        internal static string HelpLine7 {
            get {
                return ResourceManager.GetString("HelpLine7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking this option will unlock additional gameplay features that allow you to play with more numbers in the game.
        ///Please note that enabling the Extended Features will require you to reset the game. You can do this by clicking the &apos;Reset&apos; button in the Actions Bar.
        ///For more information about the Extended Features and how to use them, please refer to the &apos;How To Play&apos; guide in the About section..
        /// </summary>
        internal static string TipForExtFea {
            get {
                return ResourceManager.GetString("TipForExtFea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: This feature creates an effect of Blue Screen of Death (BSoD) if you lose the game. However, this BSoD will not actually damage your operating system.
        ///If you see the simulated BSoD, simply restart your device. This will restore normal operation without any lasting harm.
        ///However, the BSoD may cause other software you have running to unexpectedly close. To minimize disruption, please make sure to save your work and close any other open applications before proceeding with the feature.
        ///You can disable  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WarnForBSoD {
            get {
                return ResourceManager.GetString("WarnForBSoD", resourceCulture);
            }
        }
    }
}
